format = """
$directory\
[](fg:#45475a bg:#313244)\
$git_branch\
$git_status\
[](fg:#313244 bg:#1e1e2e)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1e1e2e)\
\n$character"""

[directory]
style = "fg:#cdd6f4 bg:#45475a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#45475a"
format = '[[ $symbol $branch ](fg:#a6adc8 bg:#313244)]($style)'

[git_status]
style = "bg:#45475a"
format = '[[($all_status$ahead_behind )](fg:#a6adc8 bg:#313244)]($style)'

[nodejs]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#a6adc8 bg:#1e1e2e)]($style)'

[rust]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#a6adc8 bg:#1e1e2e)]($style)'

[golang]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#a6adc8 bg:#1e1e2e)]($style)'

[php]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#a6adc8 bg:#1e1e2e)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#181825)]($style)'
